feat: add alchemy as rpc url for base sepolia
wevm/viem pull request #1602
Opened 2023-12-20 16:47 UTC by avasisht23

2023-12-20 16:56 UTC, tmm commented
FYI [Viem v2](https://github.com/wevm/viem/pull/1429) will be released soon and will no longer accept these type of pull requests because we are moving away from hardcoding provider URLs and are only going to keep track of public resources.

2023-12-20 17:57 UTC, cainaleaouk commented
Hey guys, this a huge blocker for us at the moment. Any change we could get this merged soon?

2023-12-20 18:11 UTC, avasisht23 commented
@tmm so how would devs use RPC providers like Alchemy in the future? hard-coding the URLs themselves? I found this util in viem to be quite helpful.

2023-12-20 20:27 UTC, tmm commented
You would copy the RPC URL from your providers dashboard. You already need to go there to get the API key. This way we don't need to hardcode anything.

2023-12-21 11:09 UTC, cainaleaouk commented
> You would copy the RPC URL from your providers dashboard. You already need to go there to get the API key. This way we don't need to hardcode anything.

So just making the devs life a bit harder then, for not real gain?

2023-12-21 11:11 UTC, cainaleaouk commented
Also... Any chance this can get merged, still waiting on this to unblock the migration from goerli to sepolia

2023-12-21 15:29 UTC, tmm commented
> So just making the devs life a bit harder then, for not real gain?

@cainaleaouk the only difference is you copy-paste the second or third option instead of the first.

![000278_Firefox_2023-12-21-10 27 06@2x](https://github.com/wevm/viem/assets/6759464/a34edb29-2c6a-4212-8a1f-eaaf8dd2ff10)

> Also... Any chance this can get merged, still waiting on this to unblock the migration from goerli to sepolia

Feel free to copy the code and define the chain in your repo manually while you wait! Pretty simple workaround and will unblock you.

2023-12-21 15:30 UTC, tmm requested changes
Please add a changeset with `bun changeset`

2023-12-21 18:46 UTC, cainaleaouk commented
> > So just making the devs life a bit harder then, for not real gain?
> 
> @cainaleaouk the only difference is you copy-paste the second or third option instead of the first.
> 
> ![000278_Firefox_2023-12-21-10 27 06@2x](https://private-user-images.githubusercontent.com/6759464/292247164-a34edb29-2c6a-4212-8a1f-eaaf8dd2ff10.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMxODMxODQsIm5iZiI6MTcwMzE4Mjg4NCwicGF0aCI6Ii82NzU5NDY0LzI5MjI0NzE2NC1hMzRlZGIyOS0yYzZhLTQyMTItOGExZi1lYWFmOGRkMmZmMTAucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIyMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMjFUMTgyMTI0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MjdlNmM0YWE1MWEzMzllOGVhYmVlOGNhNWZhY2MzY2I2M2IwMWUyMDYxZmFlOTJjZTU5NmUzNTdlOWY3NWQxNiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.r9Kc8c6uS51vybOx1KA05krDM-MHychAp_AVmqWe98g)
> 
> > Also... Any chance this can get merged, still waiting on this to unblock the migration from goerli to sepolia
> 
> Feel free to copy the code and define the chain in your repo manually while you wait! Pretty simple workaround and will unblock you.



> > So just making the devs life a bit harder then, for not real gain?
> 
> @cainaleaouk the only difference is you copy-paste the second or third option instead of the first.
> 
> ![000278_Firefox_2023-12-21-10 27 06@2x](https://private-user-images.githubusercontent.com/6759464/292247164-a34edb29-2c6a-4212-8a1f-eaaf8dd2ff10.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMxODMxODQsIm5iZiI6MTcwMzE4Mjg4NCwicGF0aCI6Ii82NzU5NDY0LzI5MjI0NzE2NC1hMzRlZGIyOS0yYzZhLTQyMTItOGExZi1lYWFmOGRkMmZmMTAucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIyMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMjFUMTgyMTI0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MjdlNmM0YWE1MWEzMzllOGVhYmVlOGNhNWZhY2MzY2I2M2IwMWUyMDYxZmFlOTJjZTU5NmUzNTdlOWY3NWQxNiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.r9Kc8c6uS51vybOx1KA05krDM-MHychAp_AVmqWe98g)
> 
> > Also... Any chance this can get merged, still waiting on this to unblock the migration from goerli to sepolia
> 
> Feel free to copy the code and define the chain in your repo manually while you wait! Pretty simple workaround and will unblock you.

So how about people who don't use the API key? We connect to alchemy provider via JWT, and then (not sure but that's my understanding) will take care of appending it to the url as long as it exists (in this case it doesnt).

Also your answer is not complete enough, is not copying the second link only, I need to then inject that into the chain information as I'm doing locally now to unblock myself like you pointed out.

```
const baseSepolia = SupportedChains.get(config.chainIds.baseSepolia.numId);
baseSepolia.rpcUrls.alchemy = { http: ['https://base-sepolia.g.alchemy.com/v2'] };
```

But I can't help to think it's silly to have to do that for every project we have since we already had a nice util. And the reason for not having the utils is, to me, quite weak.

Could you elaborate, so I can understand, what is your beef with the current util? Why does it hurt to have hardcoded values in the lib?

2023-12-21 19:03 UTC, jxom commented
Setting an RPC URL is something you do once and shouldn’t need to touch again. Surely that isn’t too hard? 😅

2023-12-21 19:05 UTC, tmm commented
> Why does it hurt to have hardcoded values in the lib?

Because we don't want to be the source of truth for this information and there are tens of providers (and if we let Alchemy hardcode their values, then all of them will want to).

2023-12-21 19:19 UTC, cainaleaouk commented
> Setting an RPC URL is something you do once and shouldn’t need to touch again. Surely that isn’t too hard? 😅

Not hard, just yak shaving

2023-12-27 18:10 UTC, avasisht23 commented
added @tmm

2023-12-27 18:23 UTC, tmm commented on .changeset/curvy-tips-fetch.md
> +"viem": minor
```suggestion
"viem": patch
```

2023-12-27 18:25 UTC, tmm commented on .changeset/curvy-tips-fetch.md
> +feat: add alchemy as rpc url for base sepolia
```suggestion
Added RPC URLs to Base Sepolia
```

2023-12-27 18:25 UTC, merged