feat: add alchemy as rpc url for opt sepolia
wevm/viem pull request #1603
Opened 2023-12-20 16:49 UTC by avasisht23

2023-12-20 16:55 UTC, tmm commented
FYI [Viem v2](https://github.com/wevm/viem/pull/1429) will be released soon and will no longer accept these type of pull requests because we are moving away from hardcoding provider URLs and are only going to keep track of public resources.

2023-12-21 15:30 UTC, tmm requested changes
Please add a changeset with `bun changeset`

2023-12-27 18:10 UTC, avasisht23 commented
added changeset @tmm

2023-12-27 18:23 UTC, tmm commented on .changeset/new-drinks-admire.md
> +"viem": minor
```suggestion
"viem": patch
```

2023-12-27 18:25 UTC, tmm commented on .changeset/new-drinks-admire.md
> +feat: add alchemy as rpc url for opt sepolia
```suggestion
Added RPC URLs to Optimism Sepolia
```

2023-12-27 18:26 UTC, merged