docs: Update OP Stack docs in RC
wevm/viem pull request #1612
Opened 2023-12-21 19:27 UTC by roninjin10

- Add jsdoc to decloratrs
- Add missing decorators in docs site

2023-12-21 19:40 UTC, roninjin10 commented on site/op-stack/client.md
> +For each of these new sections, you'll want to provide detailed descriptions of each action, their purposes, and examples of how to use them, much like you did for the existing sections. If you have
```suggestion

---

```

2023-12-21 19:40 UTC, roninjin10 commented on site/op-stack/client.md
> +
```suggestion
```

2023-12-22 00:21 UTC, jxom requested changes

2023-12-22 00:21 UTC, jxom commented on src/chains/opStack/abis.ts
> + * ABI For the OP Stack gas price oracle
```suggestion
 * ABI for the OP Stack [`GasPriceOracle` contract](https://github.com/ethereum-optimism/optimism/blob/develop/packages/contracts-bedrock/src/L2/GasPriceOracle.sol).
```

2023-12-22 00:21 UTC, jxom commented on src/chains/opStack/contracts.ts
> + * Predeploy contracts for op stack
```suggestion
 * Predeploy contracts for OP Stack.
```

2023-12-22 00:21 UTC, jxom commented on src/chains/opStack/decorators/publicL1.ts
> + *
```suggestion
/**
 * A suite of Public Actions for suited for development with Layer 2 (OP Stack) chains.
 * 
 * - Docs: https://viem.sh/op-stack/client.html
 *
```

2023-12-22 00:21 UTC, jxom commented on src/chains/opStack/decorators/publicL2.ts
> + *
```suggestion
/**
 * A suite of Public Actions for suited for development with Layer 2 (OP Stack) chains. 
 *
 * - Docs: https://viem.sh/op-stack/client.html
 *
```

2023-12-22 00:21 UTC, jxom commented on src/chains/opStack/decorators/walletL1.ts
> + *
```suggestion
/**
 * A suite of Wallet Actions for suited for development with Layer 2 (OP Stack) chains.
 *  
 * - Docs: https://viem.sh/op-stack/client.html
 *
```

2023-12-22 00:21 UTC, jxom commented on src/chains/opStack/decorators/walletL2.ts
> + *
```suggestion
/**
 * A suite of Wallet Actions for suited for development with Layer 2 (OP Stack) chains. 
 * 
 * - Docs: https://viem.sh/op-stack/client.html
 *
```

2023-12-25 09:09 UTC, merged