Add Multicall3 contract to Base Sepolia Chain definition
wevm/viem pull request #1684
Opened 2024-01-13 18:44 UTC by Yuripetusko

Multicall3 on Base Sepolia - https://base-sepolia.blockscout.com/address/0xcA11bde05977b3631167028862bE2a173976CA11?tab=contract

Bytecode matches

2024-01-13 18:47 UTC, Yuripetusko commented
Not sure if changeset is required here. The addition of missing multicall3 will not break anything for users, but will fix .multicall( calls those who rely on it. Let me know if I should run a changeset

2024-01-15 00:31 UTC, jxom requested changes

2024-01-15 00:31 UTC, jxom commented on .gitignore
Revert this change.

2024-01-15 00:31 UTC, jxom commented on bun.lockb
Revert this change.

2024-01-15 00:31 UTC, jxom commented on package.json
Revert this change.

2024-01-15 16:17 UTC, tmm reviewed
Add a patch changeset with `bun changeset`, then should be good to go.

2024-01-15 21:18 UTC, tmm approved these changes

2024-01-15 21:18 UTC, tmm commented on .changeset/metal-swans-itch.md
> +Add Multicall3 config to Base Sepolia chain definition
```suggestion
Added Multicall3 config to Base Sepolia chain definition
```

2024-01-15 21:19 UTC, merged

2024-01-28 22:05 UTC, mihoward21 commented
any chance this can get patched into v1? not sure i can upgrade to v2 just yet, but would love to get base sepolia added to my app (and i need multicall)

2024-01-28 22:26 UTC, jxom commented
@mihoward21 – you can just spread it directly onto the chain object.

```ts
const chain = {
  ...baseSepolia,
  contracts: {
    ...baseSepolia.contracts,
    multicall3: {
      address: '0xca11bde05977b3631167028862be2a173976ca11',
      blockCreated: 1059647,
    },
  }
} as const
```