Create blastSepolia.ts
wevm/viem pull request #1704
Opened 2024-01-17 07:53 UTC by armatrix

2024-01-17 14:45 UTC, tmm requested changes
Please add a changeset. https://github.com/wevm/viem/blob/main/.github/CONTRIBUTING.md#4-add-changeset

2024-01-17 22:31 UTC, jxom commented
And also export the chain please: https://github.com/wevm/viem/blob/main/.github/CONTRIBUTING.md#4-export-your-chain

2024-01-18 12:25 UTC, acoutts requested changes

2024-01-18 12:25 UTC, acoutts commented on src/chains/definitions/blastSepolia.ts
> +    default: {
Need to add 'public' one as well

2024-01-19 16:14 UTC, tmm requested changes
Please add a changeset following the [instructions](https://github.com/wevm/viem/blob/main/.github/CONTRIBUTING.md#4-add-changeset).

2024-01-20 06:46 UTC, merged

2024-01-26 17:43 UTC, kmjones1979 commented
Thanks for this!

2024-01-31 11:04 UTC, Solniechniy commented
Hey guys @armatrix @tmm @kmjones1979 @acoutts, I'm trying to add blastSepolia to my existing dapp and faced with error while using blastSepolia. The issue that I can't do view methods when the user not connected with wallet. Everything works when wallet connected. Was trying on the 1.21 version and also with the newest release - the same issue.

2024-02-07 19:10 UTC, armatrix commented
> Hey guys @armatrix @tmm @kmjones1979 @acoutts, I'm trying to add blastSepolia to my existing dapp and faced with error while using blastSepolia. The issue that I can't do view methods when the user not connected with wallet. Everything works when wallet connected. Was trying on the 1.21 version and also with the newest release - the same issue.

some methods has been updated in wagmi v2, assuming u r using wagmi.