Add berachain networks
wevm/viem pull request #1718
Opened 2024-01-19 04:33 UTC by xsubject

This PR adds the tesnet of the new [berachain network](https://twitter.com/berachain?lang=en)

2024-01-19 16:17 UTC, tmm requested changes

2024-01-19 16:17 UTC, tmm commented on src/chains/definitions/berachainTestnet.ts
> +      address: '0x9d1dB8253105b007DDDE65Ce262f701814B91125',
Only verified contracts are accepted.

2024-01-19 16:17 UTC, tmm commented on src/chains/definitions/berachainTestnet.ts
> +      url: 'https://artio.beratrail.io/',
```suggestion
      url: 'https://artio.beratrail.io',
```

2024-01-19 16:17 UTC, tmm commented on src/chains/definitions/berachainTestnet.ts
> +    default: { http: ['https://artio.rpc.berachain.com/'] },
```suggestion
    default: { http: ['https://artio.rpc.berachain.com'] },
```

2024-01-19 16:17 UTC, tmm commented on .changeset/nice-fishes-leave.md
> +Add berachain testnet
```suggestion
Added Berachain Testnet chain.
```

2024-01-21 08:03 UTC, jxom reviewed
Can you please get this chain listed here? https://github.com/ethereum-lists/chains

I can't seem to find it

2024-01-23 11:55 UTC, codingwithmanny commented
@jxom do you happen to know some of the maintainers? We have a PR open, but just waiting on it to get merged. https://github.com/ethereum-lists/chains/pull/4158

2024-01-23 11:56 UTC, codingwithmanny commented on src/chains/definitions/berachainTestnet.ts
> +      address: '0x9d1dB8253105b007DDDE65Ce262f701814B91125',
Will get that for you @tmm

2024-01-27 21:23 UTC, xsubject commented
@jxom I think it's ready, please check it now

2024-01-27 23:18 UTC, jxom commented on src/chains/definitions/berachainTestnet.ts
> +      address: '0x9d1dB8253105b007DDDE65Ce262f701814B91125',
Removed for now. Feel free to open another PR once verified.

2024-01-27 23:18 UTC, merged