Update to Support New chain
wevm/viem pull request #1743
Opened 2024-01-27 12:41 UTC by molecula451

OORT Mainnet Dev (Testnet)

ref: https://oortech.com

2024-01-27 12:44 UTC, molecula451 commented
the chain is available on: https://github.com/ethereum-lists/chains

https://chainlist.org/?testnets=false&search=oort
https://chainid.network

2024-01-27 20:27 UTC, jxom requested changes
Please add a changeset.

https://github.com/wevm/viem/blob/main/.github/CONTRIBUTING.md#4-add-changeset

2024-01-27 20:27 UTC, jxom commented on src/chains/index.ts
> +export { oortMainnetDev } from './definitions/oort.js'
Please alphabetize this.

2024-01-27 22:36 UTC, molecula451 commented on src/chains/index.ts
> +export { oortMainnetDev } from './definitions/oort.js'
thanks friend @jxom done at: https://github.com/wevm/viem/pull/1743/commits/aa07d97d8f25a735fb384786cb67780662f2fe47

2024-01-27 22:37 UTC, molecula451 commented
@jxom https://github.com/wevm/viem/pull/1743/commits/b3537df2b53cf0a5dc8246ccde2d4c50d2a0d2dc

2024-01-27 23:15 UTC, jxom commented on src/chains/definitions/oort.ts
> +  id: 9584236,
Is this meant to be 9700 as per chainlist?

2024-01-27 23:15 UTC, jxom commented on src/chains/index.ts
> +export { oortMainnetDev } from './definitions/oort.js'
ty friend <3

2024-01-27 23:20 UTC, molecula451 commented on src/chains/definitions/oort.ts
> +  id: 9584236,
yes correct chainId is 9700 https://github.com/wevm/viem/pull/1743/commits/363dc4abeffcb66f43abf12b7877e51ba3769663

2024-01-29 19:25 UTC, molecula451 commented
can we merge this @jxom ?

2024-01-30 02:04 UTC, jxom commented
yes we can

2024-01-30 02:05 UTC, merged

2024-01-30 02:25 UTC, molecula451 commented
stay tuned I will sent PR for the actual mainnet