Add Biconomy to third party section
wevm/viem pull request #1798
Opened 2024-02-11 22:51 UTC by VGabriel45

- Added information about the Biconomy SDK
- Included instructions for installing the SDK
- Provided an example on how to send a sponsored user operation

2024-02-12 03:38 UTC, jxom requested changes
Thanks for the PR! Please add Biconomy to the end of the list as the page here is served on a first-in-first-serve basis (exception to sponsors).

2024-02-12 07:51 UTC, VGabriel45 commented on site/pages/docs/third-party/account-abstraction.md
>  - [ZeroDev](#zerodev)
Sure.

2024-02-12 07:52 UTC, VGabriel45 commented on site/pages/docs/third-party/account-abstraction.md
> +While Account Abstraction is not built into the core `viem` library, you can use a third-party library like [Biconomy](https://docs.biconomy.io/), [permissionless.js](https://docs.pimlico.io/permissi
Done

2024-02-12 07:52 UTC, VGabriel45 commented on site/pages/docs/third-party/account-abstraction.md
> +## Biconomy
done

2024-02-13 00:17 UTC, jxom approved these changes

2024-02-13 00:17 UTC, merged