Addressing PR #989 comments and resolved
wevm/viem pull request #1894
Opened 2024-03-01 22:13 UTC by ITZSHOAIB

The main PR https://github.com/wevm/viem/pull/989 is closed because of the open comments that no one addressed.

- Added type to the getSocket function's argument config
- Resetting the `reconnectAttempts` after a successful connection.

2024-03-03 20:54 UTC, jxom reviewed
Can we please run `bun run format`? It is hard to review this diff.

2024-03-04 04:50 UTC, ITZSHOAIB commented
> Can we please run `bun run format`? It is hard to review this diff.

Done

2024-03-20 19:59 UTC, 0xRapid commented
Anything going on with it?

2024-03-20 20:07 UTC, jxom requested changes
We will need 100% test coverage for these changes.

`pnpm test:cov utils/rpc`

2024-04-03 20:41 UTC, nstylo commented
guys, how is it with this PR? This is super important. These silent disconnects/no reconnects are impacting us in production.

2024-04-03 21:00 UTC, jxom commented
See https://github.com/wevm/viem/pull/1894#pullrequestreview-1950039447.

2024-04-03 21:03 UTC, jahvi commented
I've been using the fork without any issues in production, if you need it urgently I suggest you do the same until tests are covered, the change is pretty straightforward so I'm happy taking the risk.

2024-04-04 19:34 UTC, tmm commented on src/utils/rpc.ts
> +  reconnectTimeout?: number
```suggestion
  reconnect?: boolean | undefined
  maxReconnectAttempts?: number | undefined
  reconnectTimeout?: number | undefined
```

2024-04-05 03:56 UTC, jxom commented
Planning on picking up this PR early next week (need to polish a few things and add tests) and merging it in.

2024-04-05 05:33 UTC, jxom commented
Closing in favor of #2073 – your commits are preserved so you still get the contribution!

2024-04-07 09:57 UTC, closed without merging