feat: Add Linea Sepolia chain
wevm/viem pull request #2056
Opened 2024-04-02 15:57 UTC by VGau

This PR adds the Linea Sepolia chain and updates the Linea Goerli file name from `lineaTestnet` to `lineaGoerli`.

2024-04-02 19:36 UTC, jxom requested changes

2024-04-02 19:36 UTC, jxom commented on src/chains/definitions/lineaGoerli.ts
> +export const lineaGoerli = /*#__PURE__*/ defineChain({
This is a breaking change. I suggest the following:

1. Add a new file `lineaGoerli.ts` with these contents.
2. Mark the `lineaTestnet` export as deprecated in `src/chains/index.ts` with a `/** @deprecated Use `lineaGoerli` */` comment

This means we can remove this export and file in Viem v3 (next major version).

2024-04-03 07:44 UTC, VGau commented on src/chains/definitions/lineaGoerli.ts
> +export const lineaGoerli = /*#__PURE__*/ defineChain({
Okay I will do that. Thanks :)

2024-04-03 09:00 UTC, jxom commented on src/chains/definitions/lineaGoerli.ts
> +export const lineaGoerli = /*#__PURE__*/ defineChain({
Legend.

2024-04-03 09:16 UTC, VGau commented on src/chains/definitions/lineaGoerli.ts
> +export const lineaGoerli = /*#__PURE__*/ defineChain({
Done :)

2024-04-03 20:34 UTC, merged