Add yooldo verse mainnet and testnet chains
wevm/viem pull request #2172
Opened 2024-04-23 06:51 UTC by aiiiden

The focus of this PR is to add support for two new chains, astarZkEVM and astarZkyoto.

## Detailed summary
- Added chain definition : Yooldo verse mainnet & testnet

## Reference

- https://verse.yooldo.gg
- previous ethereum list PR : https://github.com/ethereum-lists/chains/pull/3959

2024-04-23 22:37 UTC, jxom commented on src/chains/definitions/yooldoVerse.ts
> +  network: 'yooldoVerse',
```suggestion
```

2024-04-23 22:37 UTC, jxom commented on src/chains/definitions/yooldoVerseTestnet.ts
> +  network: 'yooldoVerseTestnet',
```suggestion
```

2024-04-23 22:37 UTC, jxom requested changes
Please add a changeset: `bun run changeset`

2024-04-24 08:17 UTC, aiiiden commented on src/chains/definitions/yooldoVerse.ts
> +  network: 'yooldoVerse',
Fixed with [883800e](https://github.com/wevm/viem/pull/2172/commits/883800ed9acafaf1371a3eed7f7efd6a8418ae5d)

2024-04-24 23:45 UTC, merged