Zetachain Network Updation
wevm/viem pull request #2365
Opened 2024-06-04 10:29 UTC by Kali-Decoder

This PR aims to refresh the network details of ZetaChain for both its mainnet and testnet environments. The update is likely intended to ensure Wagmi, a tool or platform that interacts with blockchain networks, has accurate information about ZetaChain. With this updated data, users of Wagmi would be able to seamlessly interact with ZetaChain through Wagmi's functionalities.
<br/>
<img width="785" alt="Screenshot 2024-06-04 at 3 58 01 PM" src="https://github.com/wevm/viem/assets/82640789/92f73227-6e61-4b63-9c40-0806e0f9c99f">

2024-06-04 11:04 UTC, fadeev commented on src/chains/definitions/zetachainAthensTestnet.ts
> +    name: "ZetaChain Athens 3 Testnet",
```suggestion
    name: "ZetaChain Testnet",
```

ZetaChain only has one testnet, so I think it's easier if we just call it "Testnet" without the "Athens" codename.

2024-06-04 11:05 UTC, fadeev commented on src/chains/definitions/zetachainAthensTestnet.ts
> +  name: "Zetachain Athens 3 Testnet",
```suggestion
  name: "ZetaChain Testnet",
```

2024-06-04 11:05 UTC, fadeev commented on src/chains/definitions/zetachain.ts
> +  nativeCurrency: { name: "Zetachain", symbol: "ZETA", decimals: 18 },
```suggestion
  nativeCurrency: { name: "ZetaChain", symbol: "ZETA", decimals: 18 },
```

2024-06-04 11:05 UTC, fadeev commented on src/chains/definitions/zetachain.ts
> +  name: "Zetachain Mainnet",
```suggestion
  name: "ZetaChain Mainnet",
```

2024-06-04 11:05 UTC, fadeev commented on src/chains/definitions/zetachain.ts
> +    default: { name: "zetachain", url: "https://explorer.zetachain.com/" },
```suggestion
    default: { name: "ZetaScan", url: "https://explorer.zetachain.com/" },
```

2024-06-04 12:43 UTC, Kali-Decoder reviewed
Done Changes

2024-06-04 22:45 UTC, jxom commented on src/chains/definitions/zetachain.ts
> +  iconUrl: "https://s2.coinmarketcap.com/static/img/coins/64x64/21259.png",
Please remove

2024-06-04 22:45 UTC, jxom commented on src/chains/definitions/zetachainAthensTestnet.ts
> +  iconUrl: "https://s2.coinmarketcap.com/static/img/coins/64x64/21259.png",
Please remove

2024-06-05 10:15 UTC, Kali-Decoder commented
Done Above Changes @jxom

2024-06-09 01:28 UTC, jxom requested changes
Please fix the formatting.

`pnpm lint`

2024-06-11 22:07 UTC, jxom commented
Please re-open once above comment is addressed.

2024-06-11 22:07 UTC, closed without merging