Add XR Sepolia chain (#1)
wevm/viem pull request #2444
Opened 2024-06-27 06:09 UTC by RealWooblay

2024-06-28 10:46 UTC, jxom commented on src/experimental/eip5792/actions/writeContracts.test.ts
> +            "transactionHash": "0x217f9a45ed86f0f83ec4215b2bb7d644300df2be450abdeb33426f0e65b4ae48",
please revert this

2024-06-28 10:46 UTC, jxom commented on src/chains/definitions/xrSepolia.ts
> +      url: 'https://xr-sepolia-testnet.explorer.caldera.xyz/',
```suggestion
      url: 'https://xr-sepolia-testnet.explorer.caldera.xyz',
```

2024-06-29 07:17 UTC, RealWooblay commented
@jxom Please review for merge

2024-06-29 13:24 UTC, jxom requested changes

2024-06-29 13:24 UTC, jxom commented on src/experimental/eip5792/actions/writeContracts.test.ts
These changes still need to be reverted.

2024-06-30 10:33 UTC, jxom approved these changes

2024-06-30 10:33 UTC, merged