fixes #2560  value type on function overload
wevm/viem pull request #2561
Opened 2024-07-30 03:13 UTC by Yuripetusko

2024-07-30 03:45 UTC, jxom approved these changes
Looks fine to me. Would be good to get @tmm eyes on it too!

2024-07-30 09:01 UTC, Yuripetusko commented on src/types/contract.ts
> +  mutability extends AbiStateMutability = AbiStateMutability,
Ideally mutability should be inferred. Also it sucks that it's a second argument of this Generic (because subsequent arguments require it), as it makes it hard to skip it if you don't want to pass it

2024-07-30 09:05 UTC, Yuripetusko commented on test/src/abis.ts
> +    {
I see that this config has a contract address, do I need to add this function to the actual contract? or it's fine to just have this dummy/placeholder abi for a contract that is not actually deployed?

2024-07-31 02:30 UTC, tmm commented
Will take a look tomorrow!

2024-08-03 13:57 UTC, Yuripetusko commented
> Will take a look tomorrow!

bump

2024-08-06 13:45 UTC, tmm requested changes
Let's revert the change to `GetValue` and update `SimulateContractParameters` directly with this logic. Also, let's add the following test. (Haven't found a quick way to get `@ts-expect-error` to work correctly in this case so might be best to remove that for now. There's a larger type refactor coming to Viem, which will fix this so allowing it to pass for the time being isn't the end of the world.)

```ts
test('https://github.com/wevm/viem/issues/2531', async () => {
  const abi = parseAbi([
    'function safeTransferFrom(address, address, uint256)',
    'function safeTransferFrom(address, address, uint256, bytes) payable',
  ])

  const res1 = await simulateContract(client, {
    address: '0x',
    abi,
    functionName: 'safeTransferFrom',
    args: ['0x', '0x', 123n],
    // @ts-expect-error
    value: 123n,
  })
  assertType<void>(res1.result)
  expectTypeOf(res1.request.abi).toEqualTypeOf(
    parseAbi(['function safeTransferFrom(address, address, uint256)']),
  )

  const res2 = await simulateContract(client, {
    address: '0x',
    abi,
    functionName: 'safeTransferFrom',
    args: ['0x', '0x', 123n, '0x'],
    value: 123n,
  })
  assertType<void>(res2.result)
  expectTypeOf(res2.request.abi).toEqualTypeOf(
    parseAbi([
      'function safeTransferFrom(address, address, uint256, bytes) payable',
    ]),
  )
})
```

In summary:
- Remove `GetValue` related changes
- Add logic directly to `SimulateContractParameters`
- Add test to `simulateContract.test-d.ts`

2024-08-06 13:45 UTC, tmm commented on src/types/contract.ts
> +  mutability extends AbiStateMutability = AbiStateMutability,
Since `GetValue` is a public API (exported in `index.ts`), let's pull this logic directly into `simulateContract.ts` for now.

2024-08-06 13:45 UTC, tmm commented on test/src/abis.ts
> +    {
Let's remove this addition to the ABI.

2024-08-06 13:45 UTC, tmm commented on src/types/contract.test-d.ts
Let's revert this change.

2024-08-06 14:11 UTC, Yuripetusko commented
> Let's revert the change to `GetValue` and update `SimulateContractParameters` directly with this logic. Also, let's add the following test. (Haven't found a quick way to get `@ts-expect-error` to work correctly in this case so might be best to remove that for now. There's a larger type refactor coming to Viem, which will fix this so allowing it to pass for the time being isn't the end of the world.)
> 
> ```ts
> test('https://github.com/wevm/viem/issues/2531', async () => {
>   const abi = parseAbi([
>     'function safeTransferFrom(address, address, uint256)',
>     'function safeTransferFrom(address, address, uint256, bytes) payable',
>   ])
> 
>   const res1 = await simulateContract(client, {
>     address: '0x',
>     abi,
>     functionName: 'safeTransferFrom',
>     args: ['0x', '0x', 123n],
>     // @ts-expect-error
>     value: 123n,
>   })
>   assertType<void>(res1.result)
>   expectTypeOf(res1.request.abi).toEqualTypeOf(
>     parseAbi(['function safeTransferFrom(address, address, uint256)']),
>   )
> 
>   const res2 = await simulateContract(client, {
>     address: '0x',
>     abi,
>     functionName: 'safeTransferFrom',
>     args: ['0x', '0x', 123n, '0x'],
>     value: 123n,
>   })
>   assertType<void>(res2.result)
>   expectTypeOf(res2.request.abi).toEqualTypeOf(
>     parseAbi([
>       'function safeTransferFrom(address, address, uint256, bytes) payable',
>     ]),
>   )
> })
> ```
> 
> In summary:
> 
> * Remove `GetValue` related changes
> * Add logic directly to `SimulateContractParameters`
> * Add test to `simulateContract.test-d.ts`

Hm the reason ts-expect-error doesn't do anything here is that parseAi only picks one of the mutability options when merging an overload

<img width="394" alt="image" src="https://github.com/user-attachments/assets/7d2a8399-7874-456a-87d9-ddd48f6276f0">

2024-08-06 14:17 UTC, tmm commented
@Yuripetusko nice find. Can drop `parseAbi` and add the object directly instead.

2024-08-06 14:24 UTC, Yuripetusko commented
> @Yuripetusko nice find. Can drop `parseAbi` and add the object directly instead.

Weirdly I can't reproduce this in here. So maybe it's my Jetbrains IDE messing with me again

https://stackblitz.com/edit/viem-getting-started-jixksa?file=package.json,index.ts

2024-08-06 15:19 UTC, Yuripetusko commented
@tmm added it to writeContract too, but lmk if I should just add it to simulateContract. Unfortunately I keep getting http errors when running all tests locally. But selected tests seems to be fine. Ignore the previous comments about parseAbi, it was due to something else entirely (missing `args` on new Generic, which is required to find the correct function in case of overloads)

2024-08-06 16:06 UTC, tmm commented on .changeset/new-hotels-sell.md
> +fixes #2560: infer the correct `value` type on function overload by matching correct function using function args
```suggestion
Fixed #2560: infer the correct payable `value` type on function overloads by matching function against `args`.
```

2024-08-06 16:07 UTC, tmm approved these changes

2024-08-06 16:11 UTC, merged