feat: change klaytn to kaia chain
wevm/viem pull request #2643
Opened 2024-08-22 07:03 UTC by 0oooooooo0

This Pull Request proposes the rebranding of the Klaytn Chain to the Kaia Chain, effective from August 29th. The changes include the following:

All instances of "Klaytn" have been updated to "Kaia" throughout the codebase and documentation.
The KlaytnBaobab testnet has been renamed to "Kairos." All references to "KlaytnBaobab" have been updated accordingly.
Please review the changes and provide feedback. If everything is in order, I would appreciate it if this PR could be merged by or before August 29th to ensure a smooth transition.

For more details about the chain rebranding, please refer to the official announcement [here](https://medium.com/kaiachain/its-official-kaia-mainnet-will-be-going-live-on-29-august-42fc10ea9583).

2024-08-22 21:24 UTC, jxom commented on src/chains/definitions/kaia.ts
> +export const kaia = /*#__PURE__*/ defineChain({
```suggestion
export const klaytn = /*#__PURE__*/ defineChain({
```

2024-08-22 21:24 UTC, jxom commented on src/chains/definitions/kairos.ts
> +export const kairos = /*#__PURE__*/ defineChain({
```suggestion
export const klaytnBaobab = /*#__PURE__*/ defineChain({
```

2024-08-22 21:25 UTC, jxom requested changes
To avoid breaking changes, can you please keep the original exports for these chains under a `/** @deprecated */` flag and also add new files for the new chains? We can keep the rebranding in the old chains too.

Example:
https://github.com/wevm/viem/blob/main/src/chains/index.ts#L226-L227

2024-08-22 22:35 UTC, 0oooooooo0 commented
> To avoid breaking changes, can you please keep the original exports for these chains under a `/** @deprecated */` flag and also add new files for the new chains? We can keep the rebranding in the old chains too.
> 
> Example: https://github.com/wevm/viem/blob/main/src/chains/index.ts#L226-L227

I completed it! thank you

2024-08-27 02:58 UTC, 0oooooooo0 commented
@jxom Do you check it? Kaia will launch after 2 days. so I hope it merges quickly

2024-08-27 03:21 UTC, merged