fix: add parseEip712Transaction util function
wevm/viem pull request #2948
Opened 2024-10-31 09:32 UTC by nikola-bozin-txfusion

2024-11-03 05:16 UTC, jxom commented on src/zksync/utils/parseEip712Transaction.ts
> +    const payload: Uint8Array = fromHex(transaction, 'bytes')
```suggestion
    const payload = fromHex(transaction, 'bytes')
```

2024-11-03 05:16 UTC, jxom commented on src/zksync/utils/parseEip712Transaction.ts
> +    }
```suggestion
    if (payload[0] !== 113) 
      throw new BaseError('transaction type must be eip712')
```

2024-11-03 05:16 UTC, jxom commented on src/zksync/utils/parseEip712Transaction.ts
> +    return constructEip712Transaction(payload)
Can we inline the contents of `constructEip712Transaction` into here?

2024-11-03 05:16 UTC, jxom commented on src/zksync/utils/parseEip712Transaction.ts
> +  }
Do we need to explicitly define this type? The `handleArrayToPaymaster` return type should be inferred.

2024-11-03 05:16 UTC, jxom commented on src/zksync/utils/parseEip712Transaction.ts
> +  function handleArrayToPaymaster(arr: Hex[]): PaymasterParams | undefined {
```suggestion
  function parsePaymasterArray(arr: Hex[]) {
```

2024-11-03 05:16 UTC, jxom commented on src/zksync/utils/parseEip712Transaction.ts
> +    }
```suggestion
    if (arr.length === 0) return undefined
```

2024-11-03 05:16 UTC, jxom commented on src/zksync/utils/parseEip712Transaction.ts
> +    }
```suggestion
    if (arr.length !== 2) 
      throw new BaseError(
        `Invalid paymaster parameters, expected to have length of 2, found ${arr.length}!`,
      )
```

2024-11-03 05:16 UTC, jxom commented
Can we please add docs for this?

2024-11-09 18:49 UTC, danijelTxFusion commented on src/zksync/utils/parseEip712Transaction.ts
> +    return constructEip712Transaction(payload)
The `constructEip712Transaction`  method is inlined.

2024-11-09 18:50 UTC, danijelTxFusion commented on src/zksync/utils/parseEip712Transaction.ts
> +  }
`PaymasterParams` is not needed and it has been removed.

2024-11-09 18:50 UTC, danijelTxFusion commented on src/zksync/utils/parseEip712Transaction.ts
> +  {
The scope is removed.

2024-11-13 04:15 UTC, jxom requested changes
See https://github.com/wevm/viem/pull/2948#issuecomment-2453300979

2024-11-14 01:41 UTC, danijelTxFusion commented
Changeset and docs are added.

2024-11-17 22:11 UTC, merged