Add Superseed Sepolia and Mainnet
wevm/viem pull request #3077
Opened 2024-11-29 14:01 UTC by 0xNikolas

This PR introduces support for the `Superseed Sepolia Testnet` and `Superseed Mainnet `by adding their definitions and exporting them from the relevant files.

**Detailed summary**

- Added a new entry for `superseedSepolia` in `src/chains/index.ts`.
- Added a new entry for `superseed` in `src/chains/index.ts`.
- Created `superseedSepolia` definition in `src/chains/definitions/superseedSepolia.ts` with:
  - ID: `53302`
  - Name: 'Superseed Sepolia'
  - Native currency: Ether (ETH)
  - RPC URL: https://sepolia.superseed.xyz
  - Block explorer: 'Superseed Sepolia Explorer'
  - `Multicall3` contract address
  - Marked as a testnet.
- Created superseed definition in src/chains/definitions/superseed.ts with:
  - ID: `5330`
  - Name: 'Superseed'
  - Native currency: Ether (ETH)
  - RPC URL: https://mainnet.superseed.xyz
  - Block explorer: 'Superseed Explorer'
  - `Multicall3` contract address

2024-11-30 16:34 UTC, jxom requested changes

2024-11-30 16:34 UTC, jxom commented on src/chains/definitions/superseed.ts
> +        address: '0x8b097CF1f9BbD9cbFD0DD561858a1FCbC8857Be0',
Can this address please be listed on Superseed's official docs or https://github.com/ethereum-optimism/superchain-registry/tree/main/superchain/configs/mainnet? Needs at least one credible reference.

2024-12-02 10:11 UTC, jxom commented
Please review comment and then reopen the PR.

2024-12-02 10:11 UTC, closed without merging

2024-12-11 13:42 UTC, 0xNikolas commented on src/chains/definitions/superseed.ts
> +        address: '0x8b097CF1f9BbD9cbFD0DD561858a1FCbC8857Be0',
yes, we'll deploy soon

2024-12-12 14:17 UTC, 0xNikolas commented on src/chains/definitions/superseed.ts
> +        address: '0x8b097CF1f9BbD9cbFD0DD561858a1FCbC8857Be0',
Added all contracts to docs: https://docs.superseed.xyz/build-on-superseed/contract-addresses/mainnet