ZKsync: account hoisting fix for `signEip712Transaction` and `sendEip712Transaction`
wevm/viem pull request #3109
Opened 2024-12-09 15:02 UTC by danijelTxFusion

Fix the account hoisting for `signEip712Transaction` and `sendEip712Transaction`. The actions only took account from parameters and did not check the account from client.

2024-12-09 15:05 UTC, petarTxFusion approved these changes

2024-12-10 09:18 UTC, jxom requested changes

2024-12-10 09:18 UTC, jxom commented on .changeset/empty-baboons-fry.md
Duplicate. Please remove.

2024-12-10 19:25 UTC, danijelTxFusion commented on .changeset/empty-baboons-fry.md
Removed.

2024-12-14 11:51 UTC, jxom commented
please rebase main

2024-12-29 20:15 UTC, merged